# Generated by Django 4.2.3 on 2023-08-16 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
